### ISSUE TITLE
Platform error light.artnet-led - Integration 'artnet-led' not found.

### ISSUE THREAD

**Issue by jhogendorn** [corb3000/ha-artnet-led#1]
On checking the configuration with HASS, it fails with the error in title.

The visual studio code plugin for editing `configuration.yaml` has a lot of linting errors as well, like 'missing command_topic' etc.

Install: via HACS on HASSOS+Supervisor, RPI4

`configuration.yaml`
```yaml
light:
  - platform: artnet-led
    host: 192.168.1.9                     # IP of Art-Net Node
    max_fps: 25                           # Max 40 per second
    refresh_every: 30                     # Resend values if no fades are running every x seconds, 0 disables automatic refresh
    universes:                            # Support for multiple universes
      0:                                  # Nr of Universe (see configuration of your Art-Net Node)
        output_correction: quadratic      # optional: output correction for the whole universe, will be used as default if nothing is set for the channel
        devices:
          - channel: 1                    # first channel of dmx dimmer
            name: Screen                  # name
            type: rgbw                    # type
            transition: 1                 # default duration of fades in sec. Will be overridden by Transition sent from HA
            output_correction: quadratic  # optional: quadratic, cubic or quadruple. Apply different dimming curves to the output. Default is None which means linear dimming
            channel_size: "16bit"         # width of the channel sent to DMX device, default "8bit", "16bit", "24bit" and "32bit" available.
          - channel: 10
            name: Floor
            type: rgbw
            transition: 1
            channel_size: "16bit"
            output_correction: quadratic
          - channel: 20
            name: High
            type: rgbw
            transition: 1
            channel_size: "16bit"
            output_correction: quadratic
```
