### ISSUE TITLE
100% brightness turns off lights completely in some cases

### ISSUE THREAD

**Issue by Breina** [corb3000/ha-artnet-led#2]
When putting a light on 100% brightness, the DMX channel values are set to 0.

```
- platform: artnet_led
  host: 192.168.1.15
  max_fps: 40
  universes:
    0:
      devices:
        - channel: 1
          name: Bureau NO
          type: dimmer
          output_correction: quadratic
          channel_size: 16bit
```

In this image, we can see that on the last image, the DMX channel values are set to `0 0`. The expected values are `255 255`.

![image](https://user-images.githubusercontent.com/3009914/131160978-6e3a5cf2-ba20-4625-b9a9-c51824d15e39.png)
